### ISSUE TITLE
Metamask wants to know account addresses

### ISSUE THREAD

**Issue by paulhauner** [flex-dapps/lighthouse-client-ui#10]
I noticed that Metamask said that this site needs permission to view eth1 addresses.

I have very little understanding of Metamask, but I was wondering if there's an option to *not* require to see users eth1 addresses? Although, as long as we have the tx hash we can know the sender, so perhaps we must always have this permission :thinking: 

@danielharrison do you have some thoughts about this? :)

**Comment by daniel-flex** [comment]
@paulhauner is that happening when opening the app or when on the funding page? The app should not engage MM until on the funding page, otherwise it's a bug.

**Comment by paulhauner** [comment]
It was happening when I "connected" (I think that's the term) Metamask to this specific app.

So it only ever happened once, since after that I was already "connected".

**Comment by daniel-flex** [comment]
Metamask requires explicit connection to applications, but if we can prevent this from happening until on the funding page then I think it's better.

**Comment by daniel-flex** [comment]
@paulhauner is this what you're seeing?

![Screen Shot 2020-10-31 at 10 32 38 am](https://user-images.githubusercontent.com/73456391/97764945-692a6e00-1b64-11eb-8cec-081834d5e7df.png)

If so, this is part of MM, see the comment above this one. I'm not getting any metamask prompts until I hit the funding page. Let me know if I'm missing something.

**Comment by paulhauner** [comment]
Here's the one I saw

![metamask](https://user-images.githubusercontent.com/6660660/97818363-1e406000-1cf6-11eb-8e02-7949e134bb76.png)

I had a look through the Metamask docs and I can't see how we could do away with the "View addresses..." permission, so I'm happy for you to close this unless you happen to know something additional :)

**Comment by daniel-flex** [comment]
@paulhauner agreed. I think this is good security on metamasks behalf. Perhaps the docs (or on-page info) could outline the process/reasons.

Closing for now
