### ISSUE TITLE
You can use the back button to re-create validators

### ISSUE THREAD

**Issue by paulhauner** [flex-dapps/lighthouse-client-ui#12]
You can use the back buttons to recreate validators, which causes an error from the server (lighthouse). That server error means that no harm is done.

Is there an easy way to prevent users from going back after they've created validators?

**Comment by daniel-flex** [comment]
Yep, should be able to put a flag in place to prevent going back once on the 'funding' screen

**Comment by daniel-flex** [comment]
@paulhauner have fixed this in commit f96b51e

**Comment by paulhauner** [comment]
I tested it and could not go back once on the funding page.

Closing as the issue is resolved.
