### ISSUE TITLE
RFC: skip the eth1 deposit submission

### ISSUE THREAD

**Issue by paulhauner** [flex-dapps/lighthouse-client-ui#6]
I don't think there's a way to skip the metamask deposit submission. I can't think of any reasonable scenario where someone might want to skip it, but I suspect there might be one.

I'd be interested to hear thoughts on providing the ability to skip deposit submission via Metamask.

**Comment by daniel-flex** [comment]
I guess if they're using this interface to just create the validators, but funding them via other avenue, then we could periodically watch the balance on that screen and once funded, progress them as normal. Currently we're watching for the TX success locally, but could also easily just watch the the balance also.

Also, providing the option to skip would be easy enough (once they're created) and push them to the dashboard with unfunded validators. This would also help with the 'waiting for sync' issue which might happen.

**Comment by paulhauner** [comment]
After reconsidering this, I don't think we should allow the user to skip.

If they don't deposit now, they need to obtain their deposit data somehow. We don't have the ability to do that.

If users want to do their own deposits, I think they should just upload keystores (functionality that hasn't yet been implemented).

So, I think we keep the current behaviour for now.
