### ISSUE TITLE
Ability to provide different hosts for VC/BN

### ISSUE THREAD

**Issue by paulhauner** [flex-dapps/lighthouse-client-ui#7]
I think it's possible that someone might use different host names for their VC/BN (e.g., if BN is on a hosted service and VC is on local machine). At the moment I believe we can only provide on hostname for both, @danielharrison what are your thoughts on this? :)

**Comment by daniel-flex** [comment]
I think it's a good idea to make it completely configurable - but maybe also good to hide that complexity behind a simple interface. Maybe just a button->modal to 'configure advanced options'?

**Comment by paulhauner** [comment]
> Maybe just a button->modal to 'configure advanced options'?

Sounds good to me!

**Comment by daniel-flex** [comment]
Will run this past design

**Comment by qnou** [comment]
Context with screenshot perhaps? @daniel-flex

**Comment by daniel-flex** [comment]
@qnou 

The designs you provided have been implemented:
![Screen Shot 2020-10-31 at 9 41 44 am](https://user-images.githubusercontent.com/73456391/97763685-79404e80-1b60-11eb-9c7d-a2b24da6700f.png)

context is:

> I think it's possible that someone might use different host names for their VC/BN (e.g., if BN is on a hosted service and VC is on local machine). At the moment I believe we can only provide on hostname for both

> I think it's a good idea to make it completely configurable - but maybe also good to hide that complexity behind a simple interface. Maybe just a button->modal to 'configure advanced options'?

So basically we need a was to configure all aspects of the BN and VC individually - but without overwhelming the user with too many options, and also considering returning users may not want to deal with all the fields again - just 'connect' 

also, see reference to #8

**Comment by daniel-flex** [comment]
merging this into #8, as it's the same UI problem
